services:
  php-be-service:
    build: ./php
    ports:
    - "8080:80"
  # go-be-service:
  #   build: ./go
  #   env_file:
  #   - ./go/.env
  #   ports:
  #     - "8081:8081"
  mariadb-service:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: maria123
      MYSQL_DATABASE: mariadb
      MYSQL_USER: maria
      MYSQL_PASSWORD: maria123
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always