services:
  php-be-service:
    profiles:
    - php
    build: ./php
    env_file:
      - ./php/.env
    ports:
    - "8080:80"
  go-be-service:
    profiles:
      - go
    build: ./go
    env_file:
    - ./go/.env
    ports:
      - "8081:8081"
    restart: always
    depends_on:
      mariadb-service:
        condition: service_started
    
  mariadb-service:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    ports:
      - "3306:3306"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always