services:
  web:
    build: .
    env_file:
      - ".env"
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
  mariadb-service:
    image: mariadb:latest
    container_name: mariadb_php
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql # Persist database data

  redis_php:
    image: redis
    ports:
      - "6379:6379"
    restart: always

volumes:
  mariadb_data:
    driver: local