services:
  go-service:
    profiles:
      - go
    build: .
    ports:
      - "8082:8081"
    restart: always
    depends_on:
      mariadb-service:
        condition: service_started
  mariadb-service:
    image: mariadb:latest
    container_name: mariadb_go
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PW}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PW}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql # Persist database data

volumes:
  mariadb_data:
    driver: local