name: Linting

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-go:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3

  lint-markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint Markdown Files
        uses: DavidAnson/markdownlint-cli2-action@v19
        with:
          globs: "**/*.md"
